### PR TITLE
Work/social auth

### PR DESCRIPTION
**Pull request by Qrivi**
This PR adds fields to `Account` and columns to the database to store references to social login services. 

`PATCH /account` was updated to allow for setting these references and `DELETE /account/reference/{referenceName}` was added to allow unlinking a social login service. #GDPR

⚠️ I've edited the existing Liquibase file rather than writing a migration script so the database needs to be wiped to apply this patch.

### CODE REVIEW

**Review by Pekket — APPROVED** [review]
🧞

**Comment by Qrivi** [comment]
Just added `DELETE /account/reference/{referenceName}` to the Postman collection and did some more testing. Confident to merge this later today so build is picked up to deploy tonight.

**Comment by Qrivi** [comment]
Will wait on PR #5 to be merged into `develop` as well so I can resolve merge conflicts in `ExceptionResolver` and we only need 1 deploy. Because I need to wipe the db manually for this one between merge and deploy. 🙂

- [x] Merge and resolve

**Comment by Qrivi** [comment]
Note that this code contains changes not fully compatible withe with what is currently on Rescado-app `develop`. For the app to work as expected it needs to be built from `work/social-auth` or [its PR](https://github.com/Rescado/rescado-app/pull/5) needs to be merged asap.

- The new app code works with the new server code (if we merge both mentioned app PR and this server PR)
- The new app code works with the old server code (if we merge mentioned app PR but not this server PR)
- The old app code **works but sends half baked data to** the new server code (if we merge this server PR but not the mentioned app PR)

Please review the appended commit.

**Pull request merged**
